import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css';
import ReduxProvider from '@/store/ReduxProvider';
import ToastProvider from '@/components/ToastProvider/ToastProvider';
import { SkeletonTheme } from 'react-loading-skeleton';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${montserrat.variable}`}>
      <body>
        <ReduxProvider>
          <SkeletonTheme
            baseColor="#313131"
            highlightColor="#b672ff"
            borderRadius={0}
          >
            {children}
          </SkeletonTheme>
          <ToastProvider />
        </ReduxProvider>
      </body>
    </html>
  );
}
